### ISSUE TITLE
[Site] Console errors during site load on IE 11

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#12]
**Steps to reproduce:**
1. Open IE 11 on Windows 10 x64;
2. Open developer tools;
3. Open site.

**Expected result:** Site is loaded. User is able to navigate through it;
**Actual result:** Site is not loaded. Errors in console appear:
DOM7011: Код на этой странице запрещает кэширование вперед и назад. Дополнительные сведения см. по адресу http://go.microsoft.com/fwlink/?LinkID=291337
vessna-wedding.herokuapp.com
HTML1300: Произошел переход.
vessna-wedding.herokuapp.com
HTML1500: Тег не может быть самозакрывающимся. Используйте явный закрывающий тег.
vessna-wedding.herokuapp.com (68,7)
SCRIPT445: Команда не поддерживается объектом
service-worker.js (1,5823)
ReferenceError: "Promise" не определено
   {
      [functions]: ,
      __proto__: { },
      description: ""Promise" не определено",
      message: ""Promise" не определено",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: "Promise" не определено
   at component (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:226630)
   at Anonymous function (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214570)
   at Anonymous function (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214810)
   at Anonymous function (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214761)
   at De (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214733)
   at Anonymous function (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214209)
   at f (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:217049)
   at r (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214111)
   at r (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:90:214138)
   at Anonymous function (https://vessna-wedding.herokuapp.com/dist/app.9a76247f3147b46d475e.js:9"
   }

CSS3111: В @font-face обнаружена неизвестная ошибка.
AkzidenzGroteskPro.eot

**Comment by followyouhome** [comment]
Already fixed on Sunday
