### ISSUE TITLE
[Site] [ie11] Console errors while navigating to menu 'Вечерние платья'

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#21]
**Steps to reproduce**
1. Open site;
2. Navigate to menu 'Вечерние платья'.

**Expected result:** User is navigated to the 'Вечерние платья' menu;
**Actual result:** User is navigated to the 'Вечерние платья' menu. The console is displaying errors.
![Screenshot_9](https://user-images.githubusercontent.com/37796643/58440227-43807600-80e1-11e9-8bec-7d3b5434aed4.jpg)
Разделитель событий навигации
Разделитель событий навигации
DOM7011: Код на этой странице запрещает кэширование вперед и назад. Дополнительные сведения см. по адресу http://go.microsoft.com/fwlink/?LinkID=291337
vessna-wedding.herokuapp.com
HTML1300: Произошел переход.
vessna-wedding.herokuapp.com
HTML1500: Тег не может быть самозакрывающимся. Используйте явный закрывающий тег.
vessna-wedding.herokuapp.com (68,7)
SCRIPT445: Команда не поддерживается объектом
service-worker.js (1,5823)
TypeError: Объект не поддерживает свойство или метод "includes"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: {
               [functions]: ,
               __proto__: null
            },
            message: "",
            name: "Error"
         },
         message: "",
         name: "TypeError"
      },
      description: "Объект не поддерживает свойство или метод "includes"",
      message: "Объект не поддерживает свойство или метод "includes"",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Объект не поддерживает свойство или метод "includes"
   at vt.methods.mouseenter (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:90:196464)
   at zt (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:11227)
   at n (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:12966)
   at o._wrapper (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:44375)"
   }

TypeError: Объект не поддерживает свойство или метод "includes"
   {
      [functions]: ,
      __proto__: { },
      description: "Объект не поддерживает свойство или метод "includes"",
      message: "Объект не поддерживает свойство или метод "includes"",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Объект не поддерживает свойство или метод "includes"
   at vt.methods.mouseleave (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:90:196564)
   at zt (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:11227)
   at n (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:12966)
   at o._wrapper (https://vessna-wedding.herokuapp.com/dist/app.76d80f397c5f51e66ad2.js:7:44375)"
   }

**Comment by followyouhome** [comment]
Sounds like luck of includes polyfill, please check is it enough or nope

**Comment by ypogarsky** [comment]
Passed.
