### ISSUE TITLE
[Admin Panel] Clicking on User's email leads to error in Console

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/vessna-wedding#6]
**Role:**
`Login - v.essna.qa.1@gmail.com
Password 123456qaB`

**Steps to reproduce:**
1. Login into Admin panel as User;
2. Navigate to 'Пользователи' page;
3. Click on any user email.

**Expected result:** TDB;
**Actual result:** packages.js:16 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'mailto:v.essna.qa.1@gmail.com' cannot be created in a document with origin 'https://vessna-wedding.herokuapp.com' and URL 'https://vessna-wedding.herokuapp.com/keystone/users?columns=name%2Cemail%2Caccess.keystone%2Caccess.content%2Caccess.subscription%2Cpassword'.
    at https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:14893
    at f (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:14786)
    at n.pushLocation (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:14853)
    at https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:26913
    at https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:26595
    at l (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:13669)
    at n.loopAsync (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:13675)
    at w (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:26440)
    at x (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:26693)
    at Object.E [as push] (https://vessna-wedding.herokuapp.com/keystone/js/packages.js:5:27082)

**Comment by followyouhome** [comment]
Let's ignore this one
